
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-8
pull_requests: [{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"rk-UCSBDiningCommonsMenuItem-backend","number":66,"title":"CRUD operations for UCSBDiningCommonsMenuItem are working properly","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/66"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-RecommendationRequest-backend","number":65,"title":"Add RecommendationRequest backend","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/65"},{"author":{"id":"MDQ6VXNlcjkxMjk0MDI1","is_bot":false,"login":"vaaniarora","name":"vaani arora"},"headRefName":"v-menuitem-backend","number":64,"title":"va - finished copying over files","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/64"},{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-Articles-CRUD","number":63,"title":"NM-Articles-CRUD","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/63"},{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"JeffreyHelpRequestFixtures","number":62,"title":"jm - created helpRequestFixtures ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/62"},{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"JeffreyHelpRequestCopies","number":61,"title":"jm - Copied over help request files from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/61"}]
