
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-8
pull_requests: [{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-HW5","number":118,"title":"Niyati hw5","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/118"},{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"JeffreyH05","number":117,"title":"JM - H05 Completed for HelpRequestIT.java and HelpRequestWebIT.java","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/117"},{"author":{"id":"U_kgDOBdHsdg","is_bot":false,"login":"charlene-patenaude","name":""},"headRefName":"cp-hw05","number":116,"title":"Cp - added integration testing and e2e testing for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/116"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-hw5","number":115,"title":"et - added integration testing and e2e testing for RecommendationRequest","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/115"},{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"rk-h05","number":114,"title":"Rk- added integration testing and e2e testing for UCSB Dining Commons Menu Item","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/114"},{"author":{"id":"MDQ6VXNlcjkxMjk0MDI1","is_bot":false,"login":"vaaniarora","name":"vaani arora"},"headRefName":"v-testing","number":113,"title":"va - added integration testing and e2e testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-8/pull/113"}]
